(in-package :cl-user)
(load "http:port;test;test-string-stream-server.lisp")
(http::start)
(load "http:port;test;test-exports.lisp")
(defun test-all ()
  (http::test "")
  (http::test "license")
  (http::test "translations.lisp")
  (http::test "generated"))

(format t "Test with (http::test \"\")~%")
(format t "Test with (http::test \"license\")~%")
(format t "Test with (http::test \"translations.lisp\")~%")
(format t "Test with (http::test \"generated\")~%")
(format t "Test all with (test-all))~%")